In [17]:
import geopandas as gpd
import glob
import numpy as np
import pandas as pd

In [5]:
basin_shp_fname = glob.glob('past_dwr_extractions/ensemble_et_202312_ave_BASIN/*.shp')[0]
basin_gdf = gpd.read_file(basin_shp_fname)

In [20]:
basin_ss = basin_gdf[['Basin_Numb', 'Basin_Subb', 'Basin_Name','Basin_Su_1','geometry']]

In [21]:
csv_fnames = glob.glob('csv_gw_basin_all_lands/*.csv')

In [22]:
basin_ss

,Basin_Numb,Basin_Subb,Basin_Name,Basin_Su_1,geometry
0,1-031,1-031,WEOTT TOWN AREA,WEOTT TOWN AREA,"POLYGON ((-3.31e+05 2.66e+05, -3.31e+05 2.66e+..."
1,3-043,3-043,RINCONADA VALLEY,RINCONADA VALLEY,"POLYGON ((-4.94e+04 -2.96e+05, -4.92e+04 -2.96..."
2,4-015,4-015,TIERRA REJADA,TIERRA REJADA,"POLYGON ((1.08e+05 -4.2e+05, 1.07e+05 -4.2e+05..."
3,8-002,8-002.03,UPPER SANTA ANA VALLEY,UPPER SANTA ANA VALLEY - RIVERSIDE-ARLINGTON,"POLYGON ((2.42e+05 -4.54e+05, 2.42e+05 -4.54e+..."
4,5-021,5-021.53,SACRAMENTO VALLEY,SACRAMENTO VALLEY - BEND,"POLYGON ((-1.81e+05 2.48e+05, -1.81e+05 2.48e+..."
...,...,...,...,...,...
509,6-047,6-047,HARPER VALLEY,HARPER VALLEY,"POLYGON ((2.12e+05 -2.97e+05, 2.13e+05 -3.01e+..."
510,3-026,3-026,WEST SANTA CRUZ TERRACE,WEST SANTA CRUZ TERRACE,"MULTIPOLYGON (((-1.82e+05 -1.07e+05, -1.82e+05..."
511,9-010,9-010,SAN PASQUAL VALLEY,SAN PASQUAL VALLEY,"POLYGON ((2.84e+05 -5.42e+05, 2.84e+05 -5.42e+..."
512,6-025,6-025,BICYCLE VALLEY,BICYCLE VALLEY,"POLYGON ((3.05e+05 -2.9e+05, 3.09e+05 -2.94e+0..."
513,7-001,7-001,LANFAIR VALLEY,LANFAIR VALLEY,"POLYGON ((4.49e+05 -3.16e+05, 4.49e+05 -3.16e+..."

In [45]:
all_data_df = pd.read_csv(csv_fnames[0])

In [46]:
all_data_df.columns

Index(['MODEL', 'DATE', 'Basin_Subb', 'Basin_Numb', 'Basin_Name', 'Basin_Su_1',
       'ET_MEAN', 'ET_MEDIAN', 'ET_PCT25', 'ET_PCT75', 'ET_STDDEV',
       'PIXEL_COUNT'],
      dtype='object')

In [53]:

all_data_df["DATE"] = pd.to_datetime(all_data_df["DATE"])

# Reformat to YYYY_MM
all_data_df["date_combo"] = all_data_df["DATE"].dt.strftime("%Y_%m")

In [55]:
# Create concatenated column for new headers

vars = ['MEAN','MEDIAN','STDDEV','PCT75','PCT25']

for v in vars:
    all_data_df[v] = (all_data_df["MODEL"].astype(str) + "_" +all_data_df["date_combo"].astype(str) + "_" +f"ET_{v}")

        
    # Pivot so basin becomes rows and concatenated values become columns
    result = all_data_df.pivot_table(
        index="Basin_Subb",
        columns=v,
        values=f"ET_{v}",
        aggfunc="first"
    )
    
merged = pd.merge(
    df1,
    df2,
    left_on="basin",
    right_on="watershed_name",
    how="left"
)

# # Optional: reset index
# result = result.reset_index()

In [56]:
result

PCT25,DISALEXI_2003_10_ET_PCT25,DISALEXI_2003_11_ET_PCT25,DISALEXI_2003_12_ET_PCT25,DISALEXI_2004_01_ET_PCT25,DISALEXI_2004_02_ET_PCT25,DISALEXI_2004_03_ET_PCT25,DISALEXI_2004_04_ET_PCT25,DISALEXI_2004_05_ET_PCT25,DISALEXI_2004_06_ET_PCT25,DISALEXI_2004_07_ET_PCT25,...,SSEBOP_2025_03_ET_PCT25,SSEBOP_2025_04_ET_PCT25,SSEBOP_2025_05_ET_PCT25,SSEBOP_2025_06_ET_PCT25,SSEBOP_2025_07_ET_PCT25,SSEBOP_2025_08_ET_PCT25,SSEBOP_2025_09_ET_PCT25,SSEBOP_2025_10_ET_PCT25,SSEBOP_2025_11_ET_PCT25,SSEBOP_2025_12_ET_PCT25
Basin_Subb,,,,,,,,,,,,,,,,,,,,,
1-001,30.0,8.0,NaN,NaN,17.0,55.0,81.0,102.0,109.0,132.0,...,31.0,51.0,64.0,78.0,72.0,64.0,49.0,37.0,20.0,13.0
1-002.01,14.0,12.0,7.0,8.0,15.0,25.0,32.0,43.0,64.0,77.0,...,6.0,22.0,35.0,61.0,83.0,63.0,33.0,15.0,10.0,7.0
1-002.02,9.0,11.0,8.0,9.0,18.0,29.0,36.0,40.0,42.0,30.0,...,15.0,32.0,50.0,54.0,46.0,35.0,23.0,14.0,10.0,6.0
1-003,11.0,10.0,9.0,12.0,20.0,28.0,40.0,40.0,42.0,33.0,...,11.0,15.0,25.0,29.0,27.0,21.0,14.0,8.0,6.0,3.0
1-004,4.0,7.0,6.0,10.0,16.0,39.0,42.0,41.0,26.0,21.0,...,23.0,33.0,30.0,12.0,15.0,13.0,15.0,14.0,14.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9-027,5.0,5.0,5.0,7.0,16.0,30.0,28.0,6.0,8.0,1.0,...,31.0,50.0,52.0,33.0,31.0,37.0,46.0,38.0,24.0,28.0
9-028,8.0,7.0,3.0,7.0,19.0,46.0,41.0,18.0,18.0,17.0,...,46.0,62.0,42.0,16.0,18.0,14.0,15.0,11.0,11.0,29.0
9-029,9.0,6.0,5.0,10.0,23.0,49.0,34.0,10.0,20.0,24.0,...,45.0,67.0,53.0,31.0,21.0,24.0,10.0,10.0,14.0,28.0
9-032,29.0,7.0,3.0,8.0,15.0,43.0,42.0,43.0,43.0,55.0,...,4.0,6.0,6.0,7.0,9.0,11.0,7.0,6.0,5.0,8.0
9-033,42.0,18.0,10.0,17.0,29.0,59.0,72.0,84.0,83.0,80.0,...,9.0,12.0,10.0,11.0,13.0,14.0,13.0,10.0,8.0,12.0